# Generated by Django 5.2.11 on 2026-02-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationExperimentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='实验', max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', '成功'), ('FAILED', '失败')], default='SUCCESS', max_length=20)),
                ('message', models.CharField(blank=True, default='', max_length=255)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('data_summary', models.JSONField(blank=True, default=dict)),
                ('metrics_summary', models.JSONField(blank=True, default=dict)),
                ('chart_payload', models.JSONField(blank=True, default=dict)),
                ('sample_recommendations', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='default', max_length=32, unique=True)),
                ('online_algorithm', models.CharField(choices=[('USER_CF', '基于用户的协同过滤'), ('ITEM_CF', '基于物品的协同过滤'), ('ALS', '交替最小二乘矩阵分解')], default='ALS', max_length=20)),
                ('behavior_weights', models.JSONField(blank=True, default=dict)),
                ('top_n', models.PositiveIntegerField(default=10)),
                ('neighbor_k', models.PositiveIntegerField(default=10)),
                ('als_factors', models.PositiveIntegerField(default=12)),
                ('als_regularization', models.DecimalField(decimal_places=4, default=0.1, max_digits=6)),
                ('als_iterations', models.PositiveIntegerField(default=8)),
                ('als_alpha', models.PositiveIntegerField(default=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
