# Generated by Django 5.2.11 on 2026-02-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
