# Generated by Django 5.2.11 on 2026-02-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('main_image', models.CharField(blank=True, default='', max_length=500)),
                ('default_spec_name', models.CharField(blank=True, default='', max_length=100)),
                ('default_price', models.IntegerField(default=0)),
                ('sales_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ON_SHELF', '上架'), ('OFF_SHELF', '下架')], default='ON_SHELF', max_length=20)),
                ('sort', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True, default='')),
                ('detail_content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='categories.productcategory')),
            ],
            options={
                'ordering': ['-sort', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(max_length=500)),
                ('sort', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(blank=True, default='', max_length=100)),
                ('spec_values', models.JSONField(blank=True, default=dict)),
                ('spec_name_text', models.CharField(blank=True, default='', max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.product')),
            ],
            options={
                'ordering': ['-is_default', 'id'],
            },
        ),
    ]
