/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AmountDisplay: typeof import('./components/common/AmountDisplay.vue')['default']
    BatchActionBar: typeof import('./components/common/BatchActionBar.vue')['default']
    BehaviorTimeline: typeof import('./components/common/BehaviorTimeline.vue')['default']
    Breadcrumb: typeof import('./components/layout/Breadcrumb.vue')['default']
    DetailDrawerLayout: typeof import('./components/common/DetailDrawerLayout.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FieldConfigManager: typeof import('./components/common/FieldConfigManager.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    ListPageScaffold: typeof import('./components/common/ListPageScaffold.vue')['default']
    MainContent: typeof import('./components/layout/MainContent.vue')['default']
    ResizableWidthPanel: typeof import('./components/common/ResizableWidthPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaDrawerForm: typeof import('./components/common/SchemaDrawerForm.vue')['default']
    SchemaFormRenderer: typeof import('./components/common/SchemaFormRenderer.vue')['default']
    SchemaSearchForm: typeof import('./components/common/SchemaSearchForm.vue')['default']
    SchemaTable: typeof import('./components/common/SchemaTable.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    StatusTag: typeof import('./components/common/StatusTag.vue')['default']
    TrendDashboardPanel: typeof import('./components/common/TrendDashboardPanel.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
