# Generated by Django 5.2.11 on 2026-02-23 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_type', models.CharField(choices=[('SEARCH', '搜索'), ('CLICK_CATEGORY', '点击分类'), ('VIEW_PRODUCT', '查看商品'), ('ADD_TO_CART', '加入购物车')], max_length=32)),
                ('target_type', models.CharField(choices=[('KEYWORD', '关键词'), ('CATEGORY', '分类'), ('PRODUCT', '商品')], max_length=32)),
                ('target_id', models.BigIntegerField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, default='', max_length=255)),
                ('source_page', models.CharField(blank=True, default='', max_length=50)),
                ('extra_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='idx_behavior_cust_time'), models.Index(fields=['behavior_type', '-created_at'], name='idx_behavior_type_time')],
            },
        ),
    ]
